### ISSUE TITLE
Weighting occasionally gives rise to an error

### ISSUE THREAD

**Issue by multipitch** [rcreagh/nsm_2#1]
The following error is encountered occasionally when running (line numbers might have changed a bit since)
```
Traceback (most recent call last):
  File "/home/sean/git/nsm_2/pq_simulation.py", line 250, in <module>
    results.append(SimulationResult(*virus_simulation.run_virus()))
  File "/home/sean/git/nsm_2/pq_simulation.py", line 162, in run_virus
    function(node)
  File "/home/sean/git/nsm_2/pq_simulation.py", line 109, in communicate
    target_node = self.select_random_neighbor(node)
  File "/home/sean/git/nsm_2/pq_simulation.py", line 120, in select_random_neighbor
    return self.weighted_random_neighbor(node)
  File "/home/sean/git/nsm_2/pq_simulation.py", line 135, in weighted_random_neighbor
    candidates, 1, p=np_weights/np_weights.sum())[0]
  File "mtrand.pyx", line 1110, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:17158)
ValueError: a must be non-empty
```

**Comment by maxwbuckley** [comment]
This is caused in the case  in which there are neighbors but they are all dead. I have fixed this now. Please highlight if it reoccurs.
